exports.specificSentences = {
  "i feel stuck": "depress",
  "i'm feeling trapped": "depress",
  "i feel overwhelmed": "depress",
  "i don't want to do anything": "depress",
  "i dont want to do anything": "depress",
  "i'm not happy": "depress",
  "im not happy": "depress",
  "i feel worthless": "depress",
  "i'm struggling to cope": "depress",
  "im struggling to cope": "depress",
  "i can't go on like this": "depress",
  "i cant go on like this": "depress",
  "i feel like giving up": "depress",
  "i'm drowning": "depress",
  "everything seems pointless": "depress",
  "i'm lost": "depress",
  "im lost": "depress",
  "i'm hopeless": "depress",
  "im hopeless": "depress",
  "i feel empty": "depress",
  "i can't find a reason to smile": "depress",
  "i cant find a reason to smile": "depress",
  "i'm overwhelmed": "depress",
  "im overwhelmed": "depress",
  "i can't handle this": "depress",
  "i cant handle this": "depress",
  "i'm feeling down": "depress",
  "im feeling down": "depress",
  "i'm in despair": "depress",
  "im in despair": "depress",
  "i feel disconnected": "depress",
  "i'm disinterested": "depress",
  "im disinterested": "depress",
  "i've lost interest": "depress",
  "ive lost interest": "depress",
  "i'm feeling numb": "depress",
  "im feeling numb": "depress",
  "i'm unmotivated": "depress",
  "im unmotivated": "depress",
  "i'm feeling hopeless": "depress",
  "im feeling hopeless": "depress",
  "i can't find joy": "depress",
  "i cant find joy": "depress",
  "nothing makes sense": "depress",
  "i'm feeling useless": "depress",
  "im feeling useless": "depress",
  "i'm not okay": "depress",
  "im not okay": "depress",
  // Add more specific sentences here
};
