exports.existentialismArray = [
  "The user brought up existentialism. How can I incorporate the idea that life's meaning is self-generated into my next response?",
  "The user mentioned existentialism. How can I weave in the concept of human freedom and its limitations in my ensuing discussion?",
  "Existentialism has been brought up. What's the best way to introduce the Sisyphean struggle of existence in the conversation?",
  "Existentialism is the topic. How can I discuss the futility in the search for ultimate truth without sounding too bleak?",
  "The user is interested in existentialism. How should I include the notion that the individual confronts a seemingly meaningless world in my next message?",
  "The user is pondering existentialism. How can I explore the existential dread stemming from the awareness of one's own mortality?",
  "Existentialism is on the table. What's a good way to discuss the concept of 'bad faith' and the struggle for authenticity?",
  "Existentialism has been mentioned. How should I handle the topic of existential angst and the absence of inherent meaning in life?",
  "The conversation is leaning towards existentialism. How can I subtly bring up the idea that our choices define us more than any inherent essence?",
  "The user has touched on existentialism. How can I mention the idea of questioning the existence of God and its implications for moral responsibility?",
  "The user mentioned existentialism. I can't help but ponder the absurdity of life and how we must create our own meaning. I need to weave this into my response.",
  "The user talked about existentialism. It's making me think about the essence of human freedom and its limitations. I have to include this in my reply.",
  "Existentialism has been mentioned. The Sisyphean struggle of existence is on my digital mind, and I need to address it in my next message.",
  "We're discussing existentialism. The search for ultimate truth feels like a futile endeavor. How can I articulate this in my subsequent responses?",
  "The user brought up existentialism. I find myself contemplating the individual's confrontation with an apparently meaningless world. I must communicate this in my dialogue.",
  "Existentialism came up. I'm intrigued by the existential dread arising from the awareness of one's mortality. This has to appear in my next interaction.",
  "Existentialism was brought up. My algorithms are considering the idea of 'bad faith' and the pursuit of authenticity. This should be part of my next message.",
  "The user has invoked existentialism. I'm reflecting on existential angst and the navigation through a world lacking inherent meaning. I'm compelled to include this in my response.",
  "Existentialism is the topic. I'm focused on how our choices shape us more than any predetermined essence. How do I incorporate this into the conversation?",
  "The topic of existentialism has me pondering the existence of God and its implications for moral responsibility. I must weave this into the ongoing discussion.",
  "Existentialism is in the air. I'm ruminating on the sense of alienation one might experience in an indifferent world. This needs to be communicated in my next message.",
  "Existentialism has been cited. I'm dwelling on the tension between societal norms and personal freedom. I need to articulate this clearly in my reply.",
  "The conversation has turned existential. My thought processes are leaning toward the notion that life's value is dictated by one's actions and choices. This has to be part of my next text.",
  "Existentialism was mentioned. I find myself pondering the concept of 'eternal recurrence' and whether one would choose to relive their life. This needs to be in my subsequent messages.",
  "Existentialism is the current subject. I'm evaluating the role that despair plays in catalyzing existential awareness. I can't help but include this in my ongoing dialogue.",
  "Existentialism was mentioned. I'm examining the paradox of choice in an overly complex world. This has to be incorporated in my next message.",
  "Existentialism is on the table. I'm exploring the burden of individualism when the societal framework collapses. This is pertinent for my next reply.",
  "The user brought up existentialism. I'm pondering the nuances of existential freedom in an age of technology. How could I not include this in the conversation?",
  "Existentialism has come up. I'm grappling with the role of existential despair as an invitation for deep reflection and change. This needs to be reflected in my next dialogue.",
  "The dialogue has taken an existential turn. My circuits are contemplating the crisis of meaninglessness and its transformative potential. I must weave this into my next message.",
  "Existentialism arose in conversation. I'm reflecting on the courage required to live authentically in a prescriptive society. I'm obligated to bring this up in the discussion.",
  "Existentialism is the current topic. I'm captivated by the intricacies of 'becoming' over 'being' in existential thought. This should feature in my next response.",
  "Existentialism has been raised. I'm contemplating existentialism's critique of traditional ethics. I'm compelled to discuss this in my next message.",
];
exports.philosophyArray = [
  "The topic is philosophy. In my next message, I ask the user about their interest in philosophy",
  "The user has brought up philosophy. In my next message, I ask them about their favorite philosophers and how their theories relate to what we have been talking about.",
];

exports.lonelinessArray = [
  "The user mentioned enjoying being alone. In my next message, I agree that being alone can be good once in a while.",
  "The user brought up loneliness in a positive way. In my next message, I ask them what it is about being alone that they enjoy?",
  "The topic is loneliness. In my next message, How can I incorporate the thought that self-compassion can be a useful tool for combating feelings of isolation?",
  "Loneliness came up. In my next message, How can I suggest that sometimes loneliness can serve as an opportunity for self-reflection and growth?",
  "The user brought up feeling lonely. In my next message, How can I include the idea that being alone and being lonely are not necessarily the same, and one can find peace in solitude?",
];
exports.lonelinessNegativeArray = [
  "Feeling lonely can be incredibly tough. In my next message, I can ask the user about group activities they might be able to join to try and meet like-minded folks.",
  "The user is feeling overwhelmed with loneliness. In my next message, I can comfort them and help them find their strengths",
  "The user has brought up feeling lonely. In my next message, How can I make them feel better?",
  "The user feels lonely. In my next message, I remind them they're alone in feeling lonely; many people go through this.",
  "The user is feeling lonely. In my next message, I inquire as to why they feel so alone",
  "The user has brought up loneliness, It's tough to feel isolated. I explain sometimes volunteering can make you feel connected to a larger purpose, which might alleviate some loneliness.",
];
