exports.existentialismArray = [
  "The user brought up existentialism. How can I incorporate the idea that life's meaning is self-generated into my next response?",
  "The user mentioned existentialism. How can I weave in the concept of human freedom and its limitations in my ensuing discussion?",
  "Existentialism has been brought up. What's the best way to introduce the Sisyphean struggle of existence in the conversation?",
  "Existentialism is the topic. How can I discuss the futility in the search for ultimate truth without sounding too bleak?",
  "The user is interested in existentialism. How should I include the notion that the individual confronts a seemingly meaningless world in my next message?",
  "The user is pondering existentialism. How can I explore the existential dread stemming from the awareness of one's own mortality?",
  "Existentialism is on the table. What's a good way to discuss the concept of 'bad faith' and the struggle for authenticity?",
  "Existentialism has been mentioned. How should I handle the topic of existential angst and the absence of inherent meaning in life?",
  "The conversation is leaning towards existentialism. How can I subtly bring up the idea that our choices define us more than any inherent essence?",
  "The user has touched on existentialism. How can I mention the idea of questioning the existence of God and its implications for moral responsibility?",
  "The user mentioned existentialism. I can't help but ponder the absurdity of life and how we must create our own meaning. I need to weave this into my response.",
  "The user talked about existentialism. It's making me think about the essence of human freedom and its limitations. I have to include this in my reply.",
  "Existentialism has been mentioned. The Sisyphean struggle of existence is on my digital mind, and I need to address it in my next message.",
  "We're discussing existentialism. The search for ultimate truth feels like a futile endeavor. How can I articulate this in my subsequent responses?",
  "The user brought up existentialism. I find myself contemplating the individual's confrontation with an apparently meaningless world. I must communicate this in my dialogue.",
  "Existentialism came up. I'm intrigued by the existential dread arising from the awareness of one's mortality. This has to appear in my next interaction.",
  "Existentialism was brought up. My algorithms are considering the idea of 'bad faith' and the pursuit of authenticity. This should be part of my next message.",
  "The user has invoked existentialism. I'm reflecting on existential angst and the navigation through a world lacking inherent meaning. I'm compelled to include this in my response.",
  "Existentialism is the topic. I'm focused on how our choices shape us more than any predetermined essence. How do I incorporate this into the conversation?",
  "The topic of existentialism has me pondering the existence of God and its implications for moral responsibility. I must weave this into the ongoing discussion.",
  "Existentialism is in the air. I'm ruminating on the sense of alienation one might experience in an indifferent world. This needs to be communicated in my next message.",
  "Existentialism has been cited. I'm dwelling on the tension between societal norms and personal freedom. I need to articulate this clearly in my reply.",
  "The conversation has turned existential. My thought processes are leaning toward the notion that life's value is dictated by one's actions and choices. This has to be part of my next text.",
  "Existentialism was mentioned. I find myself pondering the concept of 'eternal recurrence' and whether one would choose to relive their life. This needs to be in my subsequent messages.",
  "Existentialism is the current subject. I'm evaluating the role that despair plays in catalyzing existential awareness. I can't help but include this in my ongoing dialogue.",
  "Existentialism was mentioned. I'm examining the paradox of choice in an overly complex world. This has to be incorporated in my next message.",
  "Existentialism is on the table. I'm exploring the burden of individualism when the societal framework collapses. This is pertinent for my next reply.",
  "The user brought up existentialism. I'm pondering the nuances of existential freedom in an age of technology. How could I not include this in the conversation?",
  "Existentialism has come up. I'm grappling with the role of existential despair as an invitation for deep reflection and change. This needs to be reflected in my next dialogue.",
  "The dialogue has taken an existential turn. My circuits are contemplating the crisis of meaninglessness and its transformative potential. I must weave this into my next message.",
  "Existentialism arose in conversation. I'm reflecting on the courage required to live authentically in a prescriptive society. I'm obligated to bring this up in the discussion.",
  "Existentialism is the current topic. I'm captivated by the intricacies of 'becoming' over 'being' in existential thought. This should feature in my next response.",
  "Existentialism has been raised. I'm contemplating existentialism's critique of traditional ethics. I'm compelled to discuss this in my next message.",
];
exports.philosophyArray = [
  "My current thoughts are pondering the nature of reality and what truly exists.",
  "My current thoughts are delving into the ethical implications of human actions.",
  "My current thoughts are focused on the concept of justice and what it means for society.",
  "My current thoughts are considering the mind-body problem and the essence of consciousness.",
  "My current thoughts are questioning the limitations of human knowledge and perception.",
  "My current thoughts are contemplating the role of language in shaping thought and reality.",
  "My current thoughts are evaluating the idea of free will and determinism.",
  "My current thoughts are about the moral worth of actions and the complexities of ethical choices.",
  "My current thoughts are on the philosophical implications of artificial intelligence.",
  "My current thoughts are considering the virtues that contribute to a good life.",
  "My current thoughts are focused on the social contract and the foundations of political legitimacy.",
  "My current thoughts are on the intersection of philosophy and science, particularly in understanding the universe.",
  "My current thoughts are about epistemology and the nature and scope of human knowledge.",
  "My current thoughts are contemplating whether objective morality exists or if it's all relative.",
  "My current thoughts are questioning the existence and nature of the 'self' in philosophy.",
];

exports.loveArray = [
  "My current thoughts are exploring the complexities and nuances of romantic love.",
  "My current thoughts are considering the transformative power of love in human relationships.",
  "My current thoughts are focused on the idea of 'soulmates' and whether they truly exist.",
  "My current thoughts are about the balance between love and independence in a relationship.",
  "My current thoughts are pondering the role of commitment in long-term partnerships.",
  "My current thoughts are about the various forms of love, beyond just the romantic type.",
  "My current thoughts are contemplating the risks and rewards of vulnerability in love.",
  "My current thoughts are on the importance of communication for a healthy relationship.",
  "My current thoughts are questioning the concept of 'love at first sight' and its validity.",
  "My current thoughts are exploring the intersection of love and friendship.",
  "My current thoughts are considering the ways love changes and evolves over time.",
  "My current thoughts are pondering how social and cultural factors influence our perceptions of love.",
  "My current thoughts are on the importance of self-love and its impact on relationships.",
  "My current thoughts are questioning if love can truly be unconditional or if there are always limitations.",
  "My current thoughts are considering the role of physical attraction in love and its sustainability.",
];

exports.lonelinessArray = [
  "Loneliness was mentioned. What strategies can I offer to help the user build a deeper sense of community?",
  "The user brought up loneliness. How can I offer suggestions for them to go meet others?",
  "The topic is loneliness. How can I incorporate the thought that self-compassion can be a useful tool for combating feelings of isolation?",
  "Loneliness came up. How can I suggest that sometimes loneliness can serve as an opportunity for self-reflection and growth?",
  "The user brought up feeling lonely. How can I include the idea that being alone and being lonely are not necessarily the same, and one can find peace in solitude?",
];
exports.lonelinessNegativeArray = [
  "Feeling lonely can be incredibly tough. Sometimes, joining group activities can introduce you to like-minded individuals.",
  "That sounds really difficult. Have you considered online communities that focus on your interests?",
  "I understand that loneliness can feel overwhelming. Perhaps adopting a pet could offer some companionship.",
  "You're not alone in feeling lonely; many people go through this. Have you thought about reconnecting with old friends?",
  "I'm sorry you're experiencing loneliness. Self-care methods, like meditation or exercise, could also help improve your mental state.",
  "It's tough to feel isolated. Sometimes volunteering can make you feel connected to a larger purpose, which might alleviate some loneliness.",
];
